import Link from 'next/link'
import Control from './Control';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}api/topices`, { cache: 'no-store' });
  const topices = await response.json();

  return (
    <html>
      <body>
        <div className="mainPageCotainer">
          <Link href='/' className='mainPage'>Wel:come</Link>
        </div>
        
        <ul className='topiceList'>
          {
            topices.map(topice => (
              <li key={topice.id} className='topice'>
                  <Link className='topicLink' href={`/test/${topice.id}`}>
                    <div className="imgAndTitle">
                        <img className='folder' src="/images/folder.svg" alt="" srcset="" />
                        <span>{topice.title}</span>
                    </div>
                  </Link>
              </li>
            ))
          }
        </ul>
        
        <Control />

        {children}
      </body>
    </html>
  );
}

export default RootLayout;