import Link from 'next/link'
import Control from './Control';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const response = await fetch(process.env.NEXT_PUBLIC_API_URL + 'api/topices', { cache: 'no-store' });
  const topices = await response.json();

  return (
    <html>
      <body>
        <Link href='/'>Welcome</Link>
        
        <ol>
          {
            topices.map(topice => <li key={topice.id}><Link href={`/test/${topice.id}`}>{topice.title}</Link></li>)
          }
        </ol>
        
        <Control />

        {children}
      </body>
    </html>
  );
}

export default RootLayout;