import Link from 'next/link'

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Link href='/'>Welcome</Link>
        
        <ol>
          <li>
            <Link href={`/test/1`}>2023년 정보처리기사 1회차</Link>
          </li>
          <li>
            <Link href={`/test/2`}>2023년 정보처리기사 2회차</Link>
          </li>
        </ol>

        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update'>Update</Link></li>
          <li><Link href='/delete'>Delete</Link></li>
        </ul>

        {children}
      </body>
    </html>
  );
}
